-- MySQL Script generated by MySQL Workbench
-- Fri Dec  5 00:21:52 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema analyx
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema analyx
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `analyx` DEFAULT CHARACTER SET utf8 ;
USE `analyx` ;

-- -----------------------------------------------------
-- Table `analyx`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `analyx`.`user` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_user`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `analyx`.`project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `analyx`.`project` (
  `id_project` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `id_user` INT NOT NULL,
  `status_analysis` TINYINT NOT NULL,
  `generated_date` DATETIME NOT NULL,
  PRIMARY KEY (`id_project`),
  INDEX `fk_project_user1_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `fk_project_user1`
    FOREIGN KEY (`id_user`)
    REFERENCES `analyx`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `analyx`.`artifact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `analyx`.`artifact` (
  `id_artifact` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `lines_code` INT NOT NULL,
  `id_project` INT NOT NULL,
  PRIMARY KEY (`id_artifact`),
  INDEX `fk_artifact_project1_idx` (`id_project` ASC) VISIBLE,
  CONSTRAINT `fk_artifact_project1`
    FOREIGN KEY (`id_project`)
    REFERENCES `analyx`.`project` (`id_project`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `analyx`.`class_artifact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `analyx`.`class_artifact` (
  `id_class_artifact` INT NOT NULL,
  `number_attributes` INT NOT NULL,
  `dit` INT NOT NULL,
  `cbo` INT NOT NULL,
  `noc` INT NOT NULL,
  PRIMARY KEY (`id_class_artifact`),
  CONSTRAINT `fk_class_artifact_artifact1`
    FOREIGN KEY (`id_class_artifact`)
    REFERENCES `analyx`.`artifact` (`id_artifact`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `analyx`.`method_artifact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `analyx`.`method_artifact` (
  `id_method_artifact` INT NOT NULL,
  `cyclomatic_complexity` INT NOT NULL,
  `id_class_artifact` INT NOT NULL,
  PRIMARY KEY (`id_method_artifact`),
  INDEX `fk_method_artifact_class_artifact1_idx` (`id_class_artifact` ASC) VISIBLE,
  CONSTRAINT `fk_method_artifact_artifact`
    FOREIGN KEY (`id_method_artifact`)
    REFERENCES `analyx`.`artifact` (`id_artifact`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_method_artifact_class_artifact1`
    FOREIGN KEY (`id_class_artifact`)
    REFERENCES `analyx`.`class_artifact` (`id_class_artifact`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
